pull_request_title: 'feat(localize): updated translation from Crowdin'
pull_request_labels:
  - crowdin
files:
  - source: /docs/locales/en/*.json
    translation: /docs/locales/%locale%/%original_file_name%
